### ISSUE TITLE
oracle integration

### ISSUE THREAD

**Issue by s751167520** [yakshaving-art/alertsnitch#2]
May I ask if I want to replace the MYSQL data source with the ORACLE data source. Which files should be modified

**Comment by pcarranza** [comment]
Hey, @s751167520 for the record, we are running this project in [gitlab](https://gitlab.com/afirth/alertsnitch) and this is just a mirror.

This said, you need to do at least 2 things:

- Add the driver as a dependency (no clue which is the right driver for Oracle)
- Add the implementation for this engine

This could be done by adding a _backend_ argument and then picking the right one [here](https://github.com/yakshaving-art/alertsnitch/blob/master/main.go#L50) and then implement something with [this interface](https://github.com/yakshaving-art/alertsnitch/blob/master/internal/internal.go#L12) (it's basically 3 methods)

It shouldn't be hard to do at all.

**Comment by pcarranza** [comment]
FYI I just added support for Postgres, which could be useful for setting up Oracle https://github.com/yakshaving-art/alertsnitch#postgres

**Comment by pcarranza** [comment]
Ok, just for awareness, a couple of things.

1. This project is actually managed in Gitlab instead of Github.
2. In [this](https://gitlab.com/yakshaving.art/alertsnitch/-/merge_requests/25) merge request you can see how I implemented Postgres support
3. I've no idea which would be the driver for Oracle, and don't have access to an Oracle DB myself, thus I don't plan to implement this myself.
4. I do accept merge requests that add more drivers, if you want to implement it yourself, just send me a MR over the Gitlab repo and I will gladly review it.

I will close this issue hoping for the conversation to move over there.
